export interface ArtCollectionParam {
  page?: number | null;
}

// Generated by https://quicktype.io

export interface ArtCollectionModel {
  pagination: Pagination;
  data: ArtCollectionData[];
  info: Info;
  config: ArtCollectionConfig;
}

export interface ArtCollectionConfig {
  iiif_url: string;
  website_url: string;
}

export interface ArtCollectionData {
  id: number;
  title: string;
  date_start: number;
  date_end: number;
  artist_display: string;
  place_of_origin: string;
  artist_title: string;
  artist_titles: string[];
  style_id: null | string;
  style_title: null | string;
  style_titles: string[];
  material_titles: string[];
  image_id: string;
}

export interface Info {
  license_text: string;
  license_links: string[];
  version: string;
}

export interface Pagination {
  page: number;
  total: number;
  limit: number;
  offset: number;
  total_pages: number;
  current_page: number;
  next_url: string;
}
